spring:
  thymeleaf:
    cache: false
    prefix: file:./src/main/resources/templates/
    #spring.thymeleaf.prefix=classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/blog?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: root
  # Configure Hibernate DDL mode: create / update
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    #      hbm2ddl:
    #        import_files: classpath:db/data.sql
    #spring.datasource.data=classpath:/data-domain.sql,file:/c:/sql/data-reference.sql,data-complex.sql
    #spring.jpa.properties.hibernate.hbm2ddl.auto = update
    properties:
      hibernate:
        format_sql: true
